### ISSUE TITLE
Missing File

### ISSUE THREAD

**Issue by thiagodma** [michelnass/Similo2#1]
Hi @michelnass. First of all,  congrats for the great work!

I was trying to execute your code and there is a missing file. You load the file into a string in this [line](https://github.com/michelnass/Similo2/blob/main/WidgetLocator/widgetlocator/WidgetLocator.java#L1041). Could you provide this file please?

**Comment by michelnass** [comment]
Hi,

Thanks for noticing, I have now uploaded the missing file!

Regards,
/Michel

________________________________
From: Thiago Dantas ***@***.***>
Sent: Monday, November 28, 2022 8:34 PM
To: michelnass/Similo2 ***@***.***>
Cc: Michel Nass ***@***.***>; Mention ***@***.***>
Subject: [michelnass/Similo2] Missing File (Issue #1)


Hi @michelnass<https://github.com/michelnass>. First of all, congrats for the great work!

I was trying to execute your code and there is a missing file. You load the file into a string in this line<https://github.com/michelnass/Similo2/blob/main/WidgetLocator/widgetlocator/WidgetLocator.java#L1041>. Could you provide this file please?

**Comment by thiagodma** [comment]
Thanks a lot, @michelnass !
